# Generated by Django 3.0.5 on 2024-01-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
