# Generated by Django 3.0.5 on 2024-01-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_auto_20240104_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='email',
        ),
    ]
